config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
             :controllers => { :registrations => "registrations", :omniauth_callbacks => "callbacks" }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "posts#index"

  resources :users, only: [:index, :show] do
    resource :profile, only: [:edit, :update]
  end
  resources :posts, only: [:index, :create, :destroy]
  resources :likes, only: [:create, :destroy]
  resources :comments, only: [:create, :destroy]
  resources :friend_requests, only: [:create, :destroy]
  resources :friendships, only: [:create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
    validates :content, presence: true
    
    belongs_to :post
    belongs_to :user
end

app/models/friend_request.rb
class FriendRequest < ApplicationRecord
    validates_uniqueness_of :sender_id, scope: [:receiver_id]

    belongs_to :sender, class_name: "User"
    belongs_to :receiver, class_name: "User"
end

app/models/friendship.rb
class Friendship < ApplicationRecord
    validates_uniqueness_of :user_id, scope: [:friend_id]
end

app/models/like.rb
class Like < ApplicationRecord
    validates_uniqueness_of :user_id, scope: [:post_id]

    belongs_to :post
    belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
    validates :content, presence: true

    belongs_to :user
    has_many :likes
    has_many :comments

    has_one_attached :image
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user

  has_one_attached :profile_picture
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, 
         :omniauthable, omniauth_providers: %i[facebook]

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.name = auth.info.first_name + ' ' + auth.info.last_name
    end
  end

  validates :name, :password, :email, presence: true

  has_one :profile

  has_and_belongs_to_many :friends, :class_name => "User", :join_table => "friendships", :foreign_key => "user_id", :association_foreign_key => "friend_id"

  has_many :friend_requests_as_receiver, class_name: "FriendRequest", foreign_key: "receiver_id"
  has_many :received_friend_requests, through: "friend_requests_as_receiver", class_name: "User", source: "sender"

  has_many :friend_requests_as_sender, class_name: "FriendRequest", foreign_key: "sender_id"
  has_many :sent_friend_requests, through: "friend_requests_as_sender", class_name: "User", source: "receiver"

  has_many :posts
  has_many :likes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!
    before_action :configure_permitted_parameters, if: :devise_controller?

    protected

    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
        devise_parameter_sanitizer.permit(:account_update, keys: [:name, :email])
    end
end

app/controllers/callbacks_controller.rb
class CallbacksController < Devise::OmniauthCallbacksController
  def facebook
    @user = User.from_omniauth(request.env["omniauth.auth"])
    unless Profile.exists?(user_id: @user.id)
      Profile.create(user_id: @user.id)
      UserMailer.with(user: @user).welcome_email.deliver_now
    end
    sign_in_and_redirect @user
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = Comment.new(comment_params)
    if @comment.save
      flash[:success] = "You posted a comment on #{@comment.post.user.name}'s post!"
    else
      flash[:warning] = "Your comment can't be blank!"
    end
    redirect_to posts_path
  end

  def destroy
    @comment = Comment.find(params[:id])
    if @comment.delete
      flash[:success] = "Comment deleted!"
    end
    redirect_back(fallback_location: root_path)
  end

  private

  def comment_params
    params.permit(:user_id, :post_id, :content)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @like = Like.new(like_params)
    if @like.save
      flash[:success] = "You liked #{@like.post.user.name}'s post!"
    end
    redirect_back(fallback_location: root_path)
  end

  def destroy
    @like = Like.find_by(like_params)
    if @like.delete
      flash[:success] = "You unliked #{@like.post.user.name}'s post!"
    end
    redirect_back(fallback_location: root_path)
  end

  private

  def like_params
    params.permit(:user_id, :post_id)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    user_friends = current_user.friends.all.map { |friend| friend.id }
    @posts = Post.where(user_id: current_user[:id]).or(Post.where(user_id: user_friends)).order('created_at DESC').includes(:likes, :comments)
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      flash[:success] = 'Your post has been created!'
    else
      flash[:warning] = "Your post can't be blank!"
    end
    redirect_to posts_path
  end

  def destroy
    @post = Post.find(params[:id])
    if @post.delete
      flash[:success] = "Post deleted!"
    end
    redirect_back(fallback_location: root_path)
  end

  private

  def post_params
    params.permit(:user_id, :content, :image)
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def edit
    @profile = Profile.find_by(user_id: current_user[:id])
  end

  def update
    @profile = Profile.find_by(user_id: current_user[:id])
    profile_params[:birthday] = profile_params[:birthday].to_date
    
    if @profile.update(profile_params)
      flash[:success] = "Your profile has been updated!"
      redirect_to user_path(current_user[:id])
    else
      flash[:warning] = "Oops! Something went wrong..."
      redirect_to edit_user_profile_path(current_user[:id])
    end
  end

  private

  def profile_params
    params.require(:profile).permit(:bio, :location, :workplace, :school, :home_town, :relationship_status, :birthday, :profile_picture)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def index
        @not_friends = User.where.not(
            :id => (
                current_user.friends.ids +
                current_user.received_friend_requests.ids +
                current_user.sent_friend_requests.ids +
                [current_user.id]
            )
        )
        @friends = User.where(id: current_user.friends.ids)

        @sent_requests = User.where(id: current_user.sent_friend_requests.ids)
        @friendships = Friendship.where(user_id: current_user.id)
    end

    def show
        @user = User.find(params[:id])
        @posts = @user.posts.all
        @friend_requests = @user.received_friend_requests.all
    end

    private

    def is_friend?(user)
        if current_user.friends.exists?(id: user.id) || 
            current_user.friend_requests_as_receiver.exists?(id: user.id) ||
            current_user.friend_requests_as_sender.exists?(id: user.id)
            return true
        else
            return false
        end
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/friend_requests_helper.rb
module FriendRequestsHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
  def generate_like_link(post)
    check_for_like = post.likes.where(user_id: current_user[:id], post_id: post.id)
    if check_for_like.any?
      link = like_path(check_for_like.first.id)
      link_method = 'delete'
    else
      link = likes_path
      link_method = 'post'
    end
    return { link: link, link_method: link_method }
  end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def my_profile?(id)
    current_user.id == id
  end
end

app/views/posts/_comment.html.erb
<div class="container-fluid d-flex flex-row border border-darkgrey pt-2 pb-2 mt-2 rounded-lg bg-white">
  <div class="mb-2 mt-2 mr-3"><% if comment.user.profile.profile_picture.attached? %>
      <%= image_tag comment.user.profile.profile_picture.variant(resize: '40x40!'), class: "img-fluid rounded-circle" %>
    <% else %>
      <%= image_tag gravatar_image_url(comment.user.email, size: '40'), height: '40', width: '40', class: 'rounded-circle img-fluid' %>
    <% end %>
  </div>
  <div class="d-flex flex-column">
    <div><strong><%= link_to(comment.user.name, user_path(comment.user.id)) %></strong></div>
    <div><%= comment.content %></div>
    <% if comment.user.id == current_user.id %>
      <div><%= link_to('Delete', comment_path(comment.id), method: 'delete', data: {confirm: "Are you sure you want to delete this comment?"}, class: "text-primary") %></div>
    <% end %>
  </div>
</div>

app/views/posts/_comment_form.html.erb
<div class="container-fluid">
  <%= form_with model: @comment, url: comments_path, method: 'post' do |f| %>
    <div class="form-group"><%= f.text_area :content, class: "form-control" %></div>
    <%= f.hidden_field 'user_id', :value => current_user[:id] %>
    <%= f.hidden_field 'post_id', :value => post.id %>
    <%= f.submit "Comment" %>
  <% end %>
</div>

app/views/posts/_post.html.erb
<div class="container-fluid d-flex flex-row align-items-center mb-1">
  <div class="mb-2 mt-2 mr-3"><% if post.user.profile.profile_picture.attached? %>
    <%= image_tag post.user.profile.profile_picture.variant(resize: '60x60!'), class: "img-fluid rounded-circle" %>
  <% else %>
    <%= image_tag gravatar_image_url(post.user.email, size: '60'), height: '60', width: '60', class: 'rounded-circle img-fluid' %>
  <% end %></div>
  <div><strong><%= link_to(post.user.name, user_path(post.user.id)) %></strong></div>
  <% if post.user.id == current_user.id %>
    <div class="ml-auto"><%= link_to('Delete', post_path(post.id), method: 'delete', data: {confirm: "Are you sure you want to delete this post?"}, class: "text-primary") %></div>
  <% end %>
</div>
<div class="container-fluid pb-3">
<div><%= post.content %></div>
<% if post.image.attached?%>
  <div class="mt-3"><%= image_tag post.image, class: "img-fluid rounded-lg"%></div>
<% end %>
</div>
<div class="container-fluid d-flex flex-row align-content-center">
  <div class="pr-3 text-muted"><%= post.likes.all.count %><%= if post.likes.all.count == 1 then ' like ' else ' likes ' end %></div>
  <% like_link = generate_like_link(post) %>
  <%= form_with url: like_link[:link], method: like_link[:link_method] do |f| %>
    <%= f.hidden_field 'post_id', :value => post.id %>
    <%= f.hidden_field 'user_id', :value => current_user[:id] %>
    <% if like_link[:link_method] == 'post' %>
      <%= f.submit 'Like', class: "btn btn-primary btn-sm" %>
    <% else %>
      <%= f.submit 'Unlike', class: "btn btn-secondary btn-sm" %>
    <% end %>
  <% end %>
  <div class="ml-auto pb-3 text-muted"><%= post.comments.all.count %><%= if post.comments.all.count == 1 then ' comment' else ' comments' end %></div>
</div>

app/views/posts/_post_form.html.erb
<div class="container-fluid">
  <%= form_with model: @post, url: posts_path, method: 'post' do |f| %>
    <div class=""><%= f.label :content, "What's on your mind?" %>
    <%= f.text_area :content, class: "form-control" %></div>
    <%= f.hidden_field 'user_id', :value => current_user[:id] %>
    <div class="d-flex flex-row">
    <div class="mr-auto"><%= f.label :image, 'Attach an image: ', class: "ml-auto"%><br>

      <%= f.file_field :image %>
      </div>
    <div><%= f.submit "Post"%></div>
    </div>
  <% end %>
</div>

app/views/posts/_posts.html.erb
  <% if posts.empty? %>
    <div class="container-fluid border border-light bg-light rounded pt-3 pb-3 mb-3">
      <%= 'Nothing to see here' %>
    </div>
  <% else %>
    <% posts.all.each do |post| %>
    <div class="container-fluid border border-light bg-light rounded pt-3 pb-3 mb-3">
      <%= render partial: 'posts/post', locals: { post: post } %>
      <%= render partial: 'posts/comment_form', locals: { post: post } %>
      <div class="pt-3">
        <% post.comments.all.each do |comment| %>
          <div class="container-fluid d-flex flex-column">
            <%= render partial: 'posts/comment', locals: { comment: comment } %>
          </div>
        <% end %>
      </div>
    </div>
    <% end %>
  <% end %>

app/views/posts/index.html.erb
<div class="row justify-content-center">
  <div class="col-sm-6">
    <div class="container-fluid text-primary border border-primary rounded pt-3 pb-3 mb-3">
      <%= render partial: 'post_form' %>
    </div>
    <div class="d-flex flex-column">
      <%= render partial: 'posts', locals: { posts: @posts } %>
    </div>
  </div>
</div>

app/views/profiles/edit.html.erb
<div class="container-fluid">
  <%= form_with model: @profile, url: user_profile_path(current_user[:id]), method: 'put' do |f| %>
    <%= f.label :profile_picture, 'Profile picture: '%><br><br>
    <% if @profile.profile_picture.attached? %>
      <%= image_tag @profile.profile_picture.variant(resize: '200x200!'), class: 'rounded-circle' %>
    <% else %>
      <%= image_tag gravatar_image_url(current_user.email, size: 200), height: 200, width: 200, class: 'rounded-circle' %>
    <% end %><br><br>
    <div class="form-group">
      <%= f.file_field :profile_picture %>
    </div><br>
    <div class="form-group">
      <%= f.label :bio, 'Bio: '%><br>
      <%= f.text_area :bio %><br>
    </div><br>
    <div class="form-group">
      <%= f.label :location, 'Current town or city: '%><br>
      <%= f.text_field :location %><br>
    </div><br>
    <div class="form-group">
      <%= f.label :workplace, 'Workplace: '%><br>
      <%= f.text_field :workplace %><br>
    </div><br>
    <div class="form-group">
      <%= f.label :school, 'School or university: '%><br>
      <%= f.text_field :school %><br>
    </div><br>
    <div class="form-group">
      <%= f.label :home_town, 'Home town: '%><br>
      <%= f.text_field :home_town %><br>
    </div><br>
    <div class="form-group">
      <%= f.label :relationship_status, 'Relationship status: '%><br>
      <%= f.text_field :relationship_status %><br>
    </div><br>
    <div class="form-group">
      <%= f.label :birthday, 'Date of birth (dd/mm/yyyy): '%><br>
      <%= f.date_field :birthday %><br>
    </div><br>
    <div><%= f.submit 'Update' %></div>
  <% end %>
</div>

app/views/users/_friend_requests.html.erb
<div class="container-fluid border border-light pt-3 pb-3 bg-light rounded-lg">
  <% if friend_requests.empty? %>
    <%= 'No pending requests'%>
  <% else %>
    <% friend_requests.each do |request| %>
      <div class="d-flex flex-row align-items-center mb-1">
        <div class="mb-2 mt-2 mr-3"><% if request.profile.profile_picture.attached? %>
          <%= image_tag request.profile.profile_picture.variant(resize: '60x60!'), class: "img-fluid rounded-circle" %>
        <% else %>
          <%= image_tag gravatar_image_url(request.email, size: '60'), height: '60', width: '60', class: 'rounded-circle img-fluid' %>
        <% end %></div>
        <div class="mr-3"><%= link_to(request.name, user_path(request.id)) %></div>
        <div class="ml-auto"><%= form_with model: @friendship, url: friendships_path, method: 'post' do |f| %>
          <%= f.hidden_field 'user_id', :value => current_user[:id] %>
          <%= f.hidden_field 'friend_id', :value => request.id %>
          <%= f.submit "Accept" %>
        <% end %></div>
        <div><%= button_to("Decline", friend_request_path(@user.friend_requests_as_receiver.find_by(sender_id: request.id)), method: 'delete') %></div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/users/_friends.html.erb
<% if friends.empty? %>
  <div class="container-fluid bg-light pt-2 pb-2 rounded-lg">
    <%= 'No friends' %>
  </div>
<% else %>
  <% @friends.each do |user| %>
    <div class="container-fluid bg-light pt-2 pb-2 rounded-lg">
      <div class="d-flex flex-row align-items-center">
        <div class="mb-2 mt-2 mr-3"><% if user.profile.profile_picture.attached? %>
          <%= image_tag user.profile.profile_picture.variant(resize: '60x60!'), class: "img-fluid rounded-circle" %>
        <% else %>
          <%= image_tag gravatar_image_url(user.email, size: '60'), height: '60', width: '60', class: 'rounded-circle img-fluid' %>
        <% end %></div>
        <div><%= link_to(user.name, user_path(user.id)) %></div>
      </div>
    </div>
  <% end %>
<% end %>

app/views/users/_own_friends.html.erb
<% if friends.empty? %>
  <div class="container-fluid bg-light pt-2 pb-2 mb-2 rounded-lg">
    <%= 'No friends' %>
  </div>
<% else %>
  <% @friends.each do |user| %>
    <div class="container-fluid bg-light pt-2 pb-2 mb-2 rounded-lg">
      <div class="d-flex flex-row align-items-center">
        <div class="mb-2 mt-2 mr-3"><% if user.profile.profile_picture.attached? %>
          <%= image_tag user.profile.profile_picture.variant(resize: '60x60!'), class: "img-fluid rounded-circle" %>
        <% else %>
          <%= image_tag gravatar_image_url(user.email, size: '60'), height: '60', width: '60', class: 'rounded-circle img-fluid' %>
        <% end %></div>
        <div><%= link_to(user.name, user_path(user.id)) %></div>
        <div><%= button_to("Remove Friend", friendship_path(@friendships.find_by(user_id: current_user.id, friend_id: user.id)), method: "delete") %></div>
      </div>
    </div>
  <% end %>
<% end %>

app/views/users/_profile.html.erb
<div class="container-fluid border border-light bg-light pt-3 pb-3 rounded-lg">
  <div class="mb-3"><% if user.profile.profile_picture.attached? %>
    <%= image_tag user.profile.profile_picture.variant(resize: '400x400!'), class: "img-fluid rounded-lg" %>
  <% else %>
    <%= image_tag gravatar_image_url(user.email, size: '100%'), height: 'auto', width: '100%', class: "rounded-lg" %>
  <% end %></div>
  <div><div class="font-weight-bold"><%= 'Name: ' %></div><%= user.name %></div><br>
  <div><div class="font-weight-bold"><%= 'Bio: ' %></div><%= user.profile.bio %></div><br>
  <div><div class="font-weight-bold"><%= 'Current town or city: ' %></div><%= user.profile.location %></div><br>
  <div><div class="font-weight-bold"><%= 'Workplace: ' %></div><%= user.profile.workplace %></div><br>
  <div><div class="font-weight-bold"><%= 'School or university: ' %></div><%= user.profile.school %></div><br>
  <div><div class="font-weight-bold"><%= 'Home town: ' %></div><%= user.profile.home_town %></div><br>
  <div><div class="font-weight-bold"><%= 'Relationship status: ' %></div><%= user.profile.relationship_status %></div><br>
  <div><div class="font-weight-bold"><%= 'Birthday: ' %></div><%= user.profile.birthday.strftime('%-d %B') unless user.profile.birthday.nil? %></div><br>
  <% if my_profile?(user.id) %>
    <%= button_to 'Edit Profile', edit_user_profile_path(user[:id]), method: 'get', class: "btn btn-link" %>
  <% end %>
</div>

app/views/users/_request_form.html.erb
<%= form_with model: @friend_request, url: friend_requests_path, method: 'post' do |f| %>
  <%= f.hidden_field 'sender_id', :value => current_user[:id] %>
  <%= f.hidden_field 'receiver_id', :value => user.id %>
  <%= f.submit "Send Friend Request" %>
<% end %>

app/views/users/index.html.erb
<div class="row">
  <div class="col-sm-3 display-flex flex-column">
  <div class="mb-3"><h4>Your friends:</h4></div>
    <%= render partial: 'own_friends', locals: { friends: @friends } %>
  </div>
  <div class="col-sm-6 display-flex flex-column">
    <div class="mb-3"><h4>Suggested friends:</h4></div>
      <% if @not_friends.empty? %>
        <div class="container-fluid bg-light pt-2 pb-2 rounded-lg">
          <%= 'No suggested friends' %>
        </div>
      <% else %>
        <% @not_friends.each do |user| %>
          <div class="container-fluid bg-light pt-2 pb-2 mb-2 rounded-lg">
            <div class="d-flex flex-row align-items-center">
              <div class="mb-2 mt-2 mr-3"><% if user.profile.profile_picture.attached? %>
                <%= image_tag user.profile.profile_picture.variant(resize: '60x60!'), class: "img-fluid rounded-circle" %>
              <% else %>
                <%= image_tag gravatar_image_url(user.email, size: '60'), height: '60', width: '60', class: 'rounded-circle img-fluid' %>
              <% end %></div>
              <div><%= link_to(user.name, user_path(user.id)) %></div>
              <div class="ml-auto"><%= render partial: 'request_form', locals: { user: user } %></div>
            </div>
          </div>
        <% end %>
      <% end %>
  </div>
  <div class="col-sm-3 display-flex flex-column">
  <div class="mb-3"><h4>Sent friend fequests:</h4></div>
    <% if @sent_requests.empty? %>
      <div class="container-fluid bg-light pt-2 pb-2 rounded-lg">
        <%= 'Everyone has accepted your requests' %>
      </div>
    <% else %>
      <% @sent_requests.each do |user| %>
        <div class="container-fluid bg-light pt-2 pb-2 mb-2 rounded-lg">
          <div class="d-flex flex-row align-items-center">
            <div class="mb-2 mt-2 mr-3"><% if user.profile.profile_picture.attached? %>
                <%= image_tag user.profile.profile_picture.variant(resize: '60x60!'), class: "img-fluid rounded-circle" %>
              <% else %>
                <%= image_tag gravatar_image_url(user.email, size: '60'), height: '60', width: '60', class: 'rounded-circle img-fluid' %>
              <% end %></div>
            <div class="mr-3"><%= link_to(user.name, user_path(user.id)) %></div>
            <div class="ml-auto"><%= button_to("Cancel", friend_request_path(current_user.friend_requests_as_sender.find_by(receiver_id: user.id)), method: 'delete') %></div>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% if current_user.id == @user.id %>
  <div class="row">
    <div class="col-sm-3">
      <div class="d-flex flex-column">
        <div class="mb-2"><h4><%= 'Your profile:'%></h4></div>
          <%= render partial: 'profile', locals: { user: @user } %>
        </div>
      </div>
    <div class="col-sm-6 display-flex flex-column">
      <div class="mb-3"><h4><%= 'Your posts:'%></h4></div>
      <div><%= render partial: 'posts/posts', locals: { posts: @posts } %></div>
    </div>
    <div class="col-sm-3 display-flex flex-column">
      <div class="mb-3"><h4><%= 'Friend requests:'%></h4></div>
      <div><%= render partial: 'friend_requests', locals: { friend_requests: @friend_requests, user: @user } %><div>
    </div>
  </div>
<% else %>
  <div class="row">
    <div class="col-sm-3">
      <div class="d-flex flex-column">
        <div class="mb-2"><h4><%= 'Profile:'%></h4></div>
          <%= render partial: 'profile', locals: { user: @user } %>
        </div>
    </div>
    <div class="col-sm-6 display-flex flex-column">
      <div class="mb-3"><h4><%= 'Posts:'%></h4></div>
      <div><% if @user.friends.ids.include?(current_user.id) %>
        <%= render partial: 'posts/posts', locals: { posts: @posts } %>
      <% else %>
        <div class="container-fluid border border-light bg-light rounded pt-3 pb-3 mb-3">
          <%= 'You need to be friends with this user to see their posts' %>
        </div>
      <% end %>
      </div>
    </div>
    <div class="col-sm-3 display-flex flex-column">
      <div class="mb-3"><h4><%= 'Friends:'%></h4></div>
      <div>
        <%= render partial: 'friends', locals: { friends: @user.friends } %>
      </div>
    </div>
  </div>
<% end %>